version: "2"

services:
    app:
        build: docker/server
        ports:
            - "8080:80"
        env_file:
            - docker/env
        restart: always
    mysql:
        image: mysql:5.7
        env_file:
            - docker/env
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8001:80"
        environment:
            PMA_HOST: mysql
        restart: always
