version: "2"

services:
    app:
        build: docker/server
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        env_file:
            - docker/env
    mysql:
        image: mysql:5.7
        env_file:
            - docker/env
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8001:80"
        environment:
            - PMA_HOST=mysql
