services:
    app.manager.session:
        class: AppBundle\Manager\SessionManager
        arguments: ['@doctrine']

    app.manager.vote:
        class: AppBundle\Manager\VoteManager
        arguments: ['@doctrine']

    app.listener.movie:
        class: AppBundle\EventListener\MovieEventListener
        arguments: ['@doctrine', '@session.flash_bag']
        tags:
            - { name: kernel.event_subscriber }

    app.listener.vote:
        class: AppBundle\EventListener\VoteListener
        arguments: ['@doctrine', '@app.manager.session']
        tags:
            - { name: kernel.event_subscriber }

    app.form_type.vote:
        class: AppBundle\Form\VoteType
        arguments: ['@app.manager.session']
        tags:
            - { name: form.type, alias: vote }
